### ISSUE TITLE
doesn't work well with decimals

### ISSUE THREAD

**Issue by daynatem** [jonschlinkert/exponential-moving-average#1]
Example:

0.54352
0.54050
0.54309

ema on different periods (38,62 ) result the same ema

**Comment by jonschlinkert** [comment]
want to do a pr?

**Comment by lexjacobs** [comment]
@daynatem, the ema is calculated correctly internally, but is cast to a truncated string prior to outputting the result. In order to have your results show meaningful decimals in your example case, you can pass your own formatting function when invoking ema.

Example (es6):
```
const ema = require('exponential-moving-average');
let result = ema([0.54352, 0.54050, 0.54309], {
  range: 2,
  format: (n) => n.toFixed(5)
});
console.log(result);
```
(ECMA Script v5):
```
var ema = require('exponential-moving-average');
var result = ema([0.54352, 0.54050, 0.54309], {
  range: 2,
  format: function(n) {
    return n.toFixed(5);
  }
});
console.log(result);
```


`// *returns: ===> * [ '0.54201', '0.54273' ]`

**Comment by jonschlinkert** [comment]
closing based on age, and the advice given by @lexjacobs. thanks for creating the issue, and @lexjacobs thanks for the help!
